### ISSUE TITLE
Configuração air no windows

### ISSUE THREAD

**Issue by neninja** [neninja/oh-my-gowsh#1]
Criar um segundo air específico para windows, exemplo que já funciona:

```toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = ""
  cmd = "npm run build && go build -o ./tmp/main.exe cmd/web/main.go"
  delay = 1000
  exclude_dir = ["public", "node_modules", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "C:\\Users\\c01460\\badevsul\\internal\\garimpo\\tmp\\main.exe"
  include_dir = []
  include_ext = ["go", "js", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
```
